### ISSUE TITLE
Sample File Required

### ISSUE THREAD

**Issue by rakeshtembhurne** [shishir99111/market-strategy-backtester#1]
Hi, could you please add a sample file?

**Comment by shishir-sonekar** [comment]
[HDFC cash and fut data 30-01-2018.xlsx](https://github.com/shishir99111/market-strategy-backtester/files/2195210/HDFC.cash.and.fut.data.30-01-2018.1.xlsx)

This file is perfect as sample file format, having futures data download from NIFTY Web Portal. You can also, utilise this backtester for other markets as well by managing the data into this format.
