### ISSUE TITLE
How can we implement and test new strategies? 

### ISSUE THREAD

**Issue by aadityatamrakar** [shishir99111/market-strategy-backtester#2]
I am also building a service-based app into fully automated algo trading. I was searching in Github and I saw this repo. 

I would like to know more details about how this works and if possible, I can implement some good strategies. 

I also saw the deviation strategy, I think it is using options data and giving a response in put-call signals.

**Comment by shishir-sonekar** [comment]
Hey Aaditya,
you are right. Around a year back I was working for one of Veteran Stock Broker on the project to automate one of his strategies. I've also built the Backtester for testing it on Historic data (also in Github). Use can add another strategy of your in the strategy directory and start testing it.
Also, I have added instructions to setup project.
PS: show some love ⭐on the repo, if you find it adding value
